minimum_pre_commit_version: "2.9.2"
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

# I'm excluding this because it's messing up the docs.
# Will consider adding back, although this has also been
# annoying for the JSONs too.
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: "v3.1.0"
#    hooks:
#      - id: prettier

  - repo: https://github.com/rhysd/actionlint
    rev: 03d0035246f3e81f36aed592ffb4bebf33a03106  # frozen: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 91d98438175bd32e4eb14a22e50a3ec0f9e55466  # frozen: v2.2.4
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 73b0f6d59bbfcb75e17a4653d581c9dfaca13969  # frozen: v0.12.5
    hooks:
      - id: ruff
        name: Ruff
        args: [--fix]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: a4920527036bb9a3f3e6055d595849d67d0da066  # frozen: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        exclude: ^docs/

  - repo: local
    hooks:
      - id: mypy
        name: mypy - Static type checking
        description: Mypy helps ensure that we use our functions and variables correctly by checking the types.
        entry: mypy
        language: system
        types: [python]
        exclude: ^examples|^docs/
        require_serial: true

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac  # frozen: v2.4.1
    hooks:
    - id: codespell
      files: ^docs/.*\.md$
      additional_dependencies:
        - tomli
