site_name: rich-click
repo_name: ewels/rich-click
repo_url: https://github.com/ewels/rich-click
site_url: https://ewels.github.io/rich-click/
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    logo: octicons/book-16
    repo: fontawesome/brands/github
    favicon: img/dbt-linreg-favicon.png
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Noto Sans
  features:
    - navigation.instant

nav:
  - Home: index.md
  - "<code>rich-click</code> CLI tool": rich_click_cli.md
  - Configuration:
      - Overview: configuration/index.md
#  - Usage:
#      - usage/github_action.md
#      - usage/cli.md
#      - usage/docker_image.md
#  - Inputs:
#      - inputs/markdown.md
#      - inputs/direct_inputs.md
#      - inputs/config_file.md
#  - Configuration:
#      - config/overview.md
#      - config/time_limits.md
#      - config/tweaks.md
#      - config/command_setup.md
#      - config/width.md
#      - config/colours.md
#      - config/cleaning.md
#      - config/ignoring_changes.md
#  - safety.md
#  - troubleshooting.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - social
