site_name: rich-click
repo_name: ewels/rich-click
repo_url: https://github.com/ewels/rich-click
site_url: https://ewels.github.io/rich-click/
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  logo: images/favicon.png
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: navy
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: navy
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Noto Sans

nav:
  - Home: index.md
  - "<code>rich-click</code> CLI tool": rich_click_cli.md
  - Configuration:
      - Overview: configuration/index.md
#  - Usage:
#      - usage/github_action.md
#      - usage/cli.md
#      - usage/docker_image.md
#  - Inputs:
#      - inputs/markdown.md
#      - inputs/direct_inputs.md
#      - inputs/config_file.md
#  - Configuration:
#      - config/overview.md
#      - config/time_limits.md
#      - config/tweaks.md
#      - config/command_setup.md
#      - config/width.md
#      - config/colours.md
#      - config/cleaning.md
#      - config/ignoring_changes.md
#  - safety.md
#  - troubleshooting.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include:
      base_path: docs

plugins:
  - social
  # - termynal

extra_css:
  - css/termynal.css
  - css/extra.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
