[tool.black]
line-length = 120
target-version = ['py37']

[tool.mypy]
python_version = "3.8"
scripts_are_modules = "True"
strict = "True"
exclude = [
    '.*?live_style_editor\.py$'
]

[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "sdist",
    "tests/fixtures/**",
    "examples/**",
    "docs/"
]
ignore = [
    "D100",
    "D102",
    "D205",
    "E731",
    "D105",
    "D203",
    "D212"
]
line-length = 120
select = [
    "D",
    "E",
    "F",
    "W",
    "I001"
]

[tool.ruff.isort]
# Todo:
#   Add vertical hanging indent when supported.
#   https://github.com/astral-sh/ruff/issues/2600
lines-after-imports = 2
known-first-party = ["rich_click"]

[tool.pyright]
include = ["src"]
pythonVersion = "3.7"
typeCheckingMode = "basic"
executionEnvironments = [
    { root = "src" },
    { root = "tests", extra_paths = [
        "src",
    ] },
]

[tool.pytest.ini_options]
addopts = "-s -rP -vv --showlocals"
pythonpath = ["tests", "src"]
testpaths = ["tests"]
