name: Lint code
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'  # Once a month

jobs:
  pre-commit:
    if: github.event_name != 'schedule' || github.repository == 'ewels/rich-click'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          pip install --editable ".[dev]"
      - uses: pre-commit-ci/lite-action@v1.1.0
