name: Test Coverage
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
        strategy:
          matrix:
            python: [3.7.x, 3.8.x, 3.9.x, 3.10.x, 3.11.x]
            click: [7.0.*, 7.1.*, 8.0.*, 8.1.*]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          pip install '.[dev]'
          pip install --upgrade "click==$CLICK_VERSION"
        env:
          CLICK_VERSION: ${{ matrix.click }}

      - name: Run Tests
        run: pytest --cov --cov-report xml
