name: Rich-codex
on:
  workflow_dispatch:

jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3
          activate-environment: true

      - name: Install your custom tools
        run: |
          uv pip install ".[docs]"
          pip install ".[docs]"

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          use_uv: "true"
          skip_python_setup: "true"
          commit_changes: "true"
          clean_img_paths: docs/images/*.svg
          terminal_width: 80
          skip_git_checks: "true"
          working_dir: "."
