name: Test Examples
on: [push, pull_request]
jobs:
  examples:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: [3.8, 3.12, 3.13]
        click: [7.0.*, 8.0.*, 8.1.*] # Skip click 7.1 since regression coverage is strictly higher in 7.0.
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install --editable "."
          uv pip install --upgrade "click==$CLICK_VERSION"
        env:
          CLICK_VERSION: ${{ matrix.click }}

      - name: Test examples
        run: |
          for f in examples/*py
          do
            echo -e "\n\n$f"
            python "${f}" --help || exit 1;
          done
